/**
 * @swagger
 * tags:
 *   name: Media
 *   description: Media and file upload management
 */

/**
 * @swagger
 * /media/upload:
 *   post:
 *     summary: Upload a media file
 *     description: Upload an image file (jpeg, jpg, png, webp) up to 5MB.
 *     tags: [Media]
 *     requestBody:
 *       required: true
 *       content:
 *         multipart/form-data:
 *           schema:
 *             type: object
 *             properties:
 *               file:
 *                 type: string
 *                 format: binary
 *                 description: The image file to upload
 *     responses:
 *       200:
 *         description: File uploaded successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 data:
 *                   type: object
 *                   properties:
 *                     url:
 *                       type: string
 *                       format: uri
 *                       description: The public URL of the uploaded file
 *                     mediaId:
 *                       type: string
 *                       description: The unique filename generated by the server
 *       400:
 *         description: Bad Request (e.g. invalid file type or file too large)
 */
